import React from 'react'

export default async function SearchBack({searchQuery}) {
  // await new promise(executor:resolve =>setTimeout(resolve,timeout:2000))
  const dummyvariable=[
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac lacus nec leo rutrum hendrerit. Quisque venenatis consectetur mi, vitae ullamcorper ex convallis nec. Maecenas lobortis ex nec est convallis, id interdum dolor tincidunt. Aenean tincidunt augue a metus commodo, sed placerat enim cursus. Cras ac turpis eget erat dapibus aliquam eu vitae velit. Vivamus vel leo non nunc consequat posuere. Vestibulum lobortis, arcu sed eleifend tempus, mi nulla faucibus urna, ut consequat purus tortor id ipsum. Nunc eget lectus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In faucibus ante ac metus semper congue. Maecenas vitae leo non nisi aliquet rhoncus vitae nec ipsum. Fusce ac nisi vitae justo vulputate suscipit. Sed facilisis metus in ligula lacinia, id aliquet turpis ullamcorper. Vivamus in eleifend odio, at consectetur nisl. Sed eget nulla eget nisi rhoncus fermentum.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac lacus nec leo rutrum hendrerit. Quisque venenatis consectetur mi, vitae ullamcorper ex convallis nec. Maecenas lobortis ex nec est convallis, id interdum dolor tincidunt. Aenean tincidunt augue a metus commodo, sed placerat enim cursus. Cras ac turpis eget erat dapibus aliquam eu vitae velit. Vivamus vel leo non nunc consequat posuere. Vestibulum lobortis, arcu sed eleifend tempus, mi nulla faucibus urna, ut consequat purus tortor id ipsum. Nunc eget lectus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In faucibus ante ac metus semper congue. Maecenas vitae leo non nisi aliquet rhoncus vitae nec ipsum. Fusce ac nisi vitae justo vulputate suscipit. Sed facilisis metus in ligula lacinia, id aliquet turpis ullamcorper. Vivamus in eleifend odio, at consectetur nisl. Sed eget nulla eget nisi rhoncus fermentum.",
]
 
  const data="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac lacus nec leo rutrum hendrerit. Quisque venenatis consectetur mi, vitae ullamcorper ex convallis nec. Maecenas lobortis ex nec est convallis, id interdum dolor tincidunt. Aenean tincidunt augue a metus commodo, sed placerat enim cursus. Cras ac turpis eget erat dapibus aliquam eu vitae velit. Vivamus vel leo non nunc consequat posuere. Vestibulum lobortis, arcu sed eleifend tempus, mi nulla faucibus urna, ut consequat purus tortor id ipsum. Nunc eget lectus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In faucibus ante ac metus semper congue. Maecenas vitae leo non nisi aliquet rhoncus vitae nec ipsum. Fusce ac nisi vitae justo vulputate suscipit. Sed facilisis metus in ligula lacinia, id aliquet turpis ullamcorper. Vivamus in eleifend odio, at consectetur nisl. Sed eget nulla eget nisi rhoncus fermentum."
  
  return  data
}
